import io
import pytest
from PIL import Image, ExifTags
from exif_analysis import extract_exif, format_exif_summary

def _create_jpeg_with_exif(exif_dict: dict) -> bytes:
    """Helper to create a JPEG in memory with specific EXIF data."""
    img = Image.new("RGB", (10, 10), color="red")
    
    # We need to construct an Exif object
    exif = img.getexif()
    for k, v in exif_dict.items():
        exif[k] = v
        
    out = io.BytesIO()
    img.save(out, format="JPEG", exif=exif)
    return out.getvalue()

def test_real_jpeg_has_exif():
    # 271: Make, 272: Model
    jpeg_bytes = _create_jpeg_with_exif({271: "Canon", 272: "EOS 5D"})
    
    result = extract_exif(jpeg_bytes)
    assert result["has_exif"] is True
    assert result["make"] == "Canon"
    assert result["model"] == "EOS 5D"
    assert result["suspicious"] is False
    assert result["ai_software_detected"] is False
    
def test_png_has_no_exif():
    img = Image.new("RGB", (10, 10), color="blue")
    out = io.BytesIO()
    img.save(out, format="PNG")
    png_bytes = out.getvalue()
    
    result = extract_exif(png_bytes)
    assert result["has_exif"] is False
    assert result["suspicious"] is True
    
def test_ai_software_tag_detected():
    # 305: Software
    jpeg_bytes = _create_jpeg_with_exif({305: "Generated by DALL-E 3"})
    
    result = extract_exif(jpeg_bytes)
    assert result["has_exif"] is True
    assert result["software"] == "Generated by DALL-E 3"
    assert result["ai_software_detected"] is True
    assert result["suspicious"] is True
    
def test_suspicious_is_true_when_no_exif():
    img = Image.new("RGB", (10, 10), color="green")
    out = io.BytesIO()
    # Save JPEG without EXIF
    img.save(out, format="JPEG")
    jpeg_bytes = out.getvalue()
    
    result = extract_exif(jpeg_bytes)
    assert result["has_exif"] is False
    assert result["suspicious"] is True
    assert "No EXIF metadata found" in result["suspicion_reason"]

def test_suspicious_is_true_when_ai_software():
    jpeg_bytes = _create_jpeg_with_exif({305: "Stable Diffusion"})
    result = extract_exif(jpeg_bytes)
    
    assert result["has_exif"] is True
    assert result["ai_software_detected"] is True
    assert result["suspicious"] is True
    assert "AI image generator" in result["suspicion_reason"]
    
def test_extract_exif_never_raises():
    # Garbage bytes
    garbage = b"this is not an image"
    res1 = extract_exif(garbage)
    assert res1["has_exif"] is False
    
    # Empty bytes
    res2 = extract_exif(b"")
    assert res2["has_exif"] is False
    
    # Truncated JPEG
    img = Image.new("RGB", (10, 10), color="red")
    out = io.BytesIO()
    img.save(out, format="JPEG")
    truncated = out.getvalue()[:10]
    
    res3 = extract_exif(truncated)
    assert res3["has_exif"] is False
